# Generated by Django 5.0.4 on 2025-02-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
    ]
