# Generated by Django 5.0.4 on 2025-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
